# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\tevents.v1\"B\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\"C\n\x12\x43reateEventRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"0\n\rEventResponse\x12\x1f\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x10.events.v1.Event\"\x12\n\x10GetEventsRequest\"5\n\x11\x45ventListResponse\x12 \n\x06\x65vents\x18\x01 \x03(\x0b\x32\x10.events.v1.Event2\x9f\x01\n\rEventsService\x12\x46\n\x0b\x43reateEvent\x12\x1d.events.v1.CreateEventRequest\x1a\x18.events.v1.EventResponse\x12\x46\n\tGetEvents\x12\x1b.events.v1.GetEventsRequest\x1a\x1c.events.v1.EventListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=27
  _globals['_EVENT']._serialized_end=93
  _globals['_CREATEEVENTREQUEST']._serialized_start=95
  _globals['_CREATEEVENTREQUEST']._serialized_end=162
  _globals['_EVENTRESPONSE']._serialized_start=164
  _globals['_EVENTRESPONSE']._serialized_end=212
  _globals['_GETEVENTSREQUEST']._serialized_start=214
  _globals['_GETEVENTSREQUEST']._serialized_end=232
  _globals['_EVENTLISTRESPONSE']._serialized_start=234
  _globals['_EVENTLISTRESPONSE']._serialized_end=287
  _globals['_EVENTSSERVICE']._serialized_start=290
  _globals['_EVENTSSERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
