apiVersion: v1
kind: Service
metadata:
  name: events-service
  labels:
    app: events-app
spec:
  type: ClusterIP
  selector:
    app: events-app
  ports:
    - name: grpc
      protocol: TCP
      port: 8277       
      targetPort: 8277 